




export const REQUEST_ROUNDS_FINISHED   = 'REQUEST_ROUNDS_FINISHED'
export const RECEIVED_ROUNDS_FINISHED  = 'RECEIVED_ROUNDS_FINISHED'
export const ERROR_ROUNDS_FINISHED     = 'ERROR_ROUNDS_FINISHED'

export const REQUEST_ROUND_INFO   = 'REQUEST_ROUND_INFO'
export const RECEIVED_ROUND_INFO  = 'RECEIVED_ROUND_INFO'
export const ERROR_ROUND_INFO     = 'ERROR_ROUND_INFO'

export const SET_ROUND_INFO = 'SET_ROUND_INFO'

export const REQUEST_ROUND_ANALYST_INFO   = 'REQUEST_ROUND_ANALYST_INFO'
export const RECEIVED_ROUND_ANALYST_INFO  = 'RECEIVED_ROUND_ANALYST_INFO'
export const ERROR_ROUND_ANALYST_INFO     = 'ERROR_ROUND_ANALYST_INFO'

export const REQUEST_SURVEY_SUBMIT  = 'REQUEST_SURVEY_SUBMIT'
export const RECEIVED_SURVEY_SUBMIT  = 'RECEIVED_SURVEY_SUBMIT'
export const ERROR_SURVEY_SUBMIT     = 'ERROR_SURVEY_SUBMIT'


export const REQUEST_TOKENS_DATA   = 'REQUEST_TOKENS_DATA'
export const RECEIVED_TOKENS_DATA  = 'RECEIVED_TOKENS_DATA'
export const ERROR_TOKENS_DATA     = 'ERROR_TOKENS_DATA'

// ethplorer combined with veva
export const REQUEST_TOKEN_DATA   = 'REQUEST_TOKEN_DATA' // getTokenInfo
export const RECEIVED_TOKEN_DATA  = 'RECEIVED_TOKEN_DATA'
export const ERROR_TOKEN_DATA     = 'ERROR_TOKEN_DATA'

export const REQUEST_TOKEN_ROUNDS   = 'REQUEST_TOKEN_ROUNDS' // getTokenInfo
export const RECEIVED_TOKEN_ROUNDS  = 'RECEIVED_TOKEN_ROUNDS'
export const ERROR_TOKEN_ROUNDS     = 'ERROR_TOKEN_ROUNDS'

