


export const REQUEST_CYCLES_DATA   = 'REQUEST_CYCLES_DATA'
export const RECEIVED_CYCLES_DATA  = 'RECEIVED_CYCLES_DATA'
export const ERROR_CYCLES_DATA     = 'ERROR_CYCLES_DATA'

export const REQUEST_CRON_INFO     = 'REQUEST_CRON_INFO'
export const RECEIVED_CRON_INFO    = 'RECEIVED_CRON_INFO'
export const ERROR_CRON_INFO       = 'ERROR_CRON_INFO'

export const REQUEST_PULSE_CRON    = 'REQUEST_PULSE_CRON'
export const RECEIVED_PULSE_CRON   = 'RECEIVED_PULSE_CRON'
export const ERROR_PULSE_CRON      = 'ERROR_PULSE_CRON'

export const REQUEST_CYCLE_SIGNUP  = 'REQUEST_CYCLE_SIGNUP'
export const RECEIVED_CYCLE_SIGNUP = 'RECEIVED_CYCLE_SIGNUP'
export const ERROR_CYCLE_SIGNUP    = 'ERROR_CYCLE_SIGNUP'

export const REQUEST_CYCLE_CONFIRM  = 'REQUEST_CYCLE_CONFIRM'
export const RECEIVED_CYCLE_CONFIRM = 'RECEIVED_CYCLE_CONFIRM'
export const ERROR_CYCLE_CONFIRM    = 'ERROR_CYCLE_CONFIRM'

export const REQUEST_ROUNDS_FINISHED   = 'REQUEST_ROUNDS_FINISHED'
export const RECEIVED_ROUNDS_FINISHED  = 'RECEIVED_ROUNDS_FINISHED'
export const ERROR_ROUNDS_FINISHED     = 'ERROR_ROUNDS_FINISHED'

export const REQUEST_ROUND_INFO   = 'REQUEST_ROUND_INFO'
export const RECEIVED_ROUND_INFO  = 'RECEIVED_ROUND_INFO'
export const ERROR_ROUND_INFO     = 'ERROR_ROUND_INFO'

export const SET_ROUND_INFO = 'SET_ROUND_INFO'

export const REQUEST_ROUND_ANALYST_INFO   = 'REQUEST_ROUND_ANALYST_INFO'
export const RECEIVED_ROUND_ANALYST_INFO  = 'RECEIVED_ROUND_ANALYST_INFO'
export const ERROR_ROUND_ANALYST_INFO     = 'ERROR_ROUND_ANALYST_INFO'

export const REQUEST_SURVEY_SUBMIT  = 'REQUEST_SURVEY_SUBMIT'
export const RECEIVED_SURVEY_SUBMIT  = 'RECEIVED_SURVEY_SUBMIT'
export const ERROR_SURVEY_SUBMIT     = 'ERROR_SURVEY_SUBMIT'


export const REQUEST_TOKENS_DATA   = 'REQUEST_TOKENS_DATA'
export const RECEIVED_TOKENS_DATA  = 'RECEIVED_TOKENS_DATA'
export const ERROR_TOKENS_DATA     = 'ERROR_TOKENS_DATA'

// ethplorer combined with veva
export const REQUEST_TOKEN_DATA   = 'REQUEST_TOKEN_DATA' // getTokenInfo
export const RECEIVED_TOKEN_DATA  = 'RECEIVED_TOKEN_DATA'
export const ERROR_TOKEN_DATA     = 'ERROR_TOKEN_DATA'

export const REQUEST_TOKEN_ROUNDS   = 'REQUEST_TOKEN_ROUNDS' // getTokenInfo
export const RECEIVED_TOKEN_ROUNDS  = 'RECEIVED_TOKEN_ROUNDS'
export const ERROR_TOKEN_ROUNDS     = 'ERROR_TOKEN_ROUNDS'

export const SET_TOKEN_SELECTED			= 'SET_TOKEN_SELECTED'

export const SET_SURVEY_QUESTION_DATA = 'SET_SURVEY_QUESTION_DATA'
export const CLEAR_SURVEY_DATA = 'CLEAR_SURVEY_DATA'
